env:
  browser: true
  es2021: true
extends:
  - standard
  - eslint:recommended
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
  - plugin:@typescript-eslint/eslint-recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
globals: 
  wx: true
  App: true
  Page: true
  Component: true
  getApp: true
  getCurrentPage: true
plugins:
  - '@typescript-eslint'
rules: {
  'no-unused-vars': 'off',
  'no-use-before-define': 'off',
  'no-param-reassign': 'error',
  'spaced-comment': ['error', 'always', { markers: ['/'] }],
  'eol-last': ['error', 'always']
}
